services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cashFlower
      MYSQL_DATABASE: cashFlow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: